import pytest

PYTEST_SLOW_MARKER = pytest.mark.slow
PYTEST_INTEGRATION_MARKER = pytest.mark.integration
PYTEST_MANUAL_MARKER = pytest.mark.manual

PYTEST_INTEGRATION_TEST_MARKERS = [
    PYTEST_SLOW_MARKER,
    PYTEST_INTEGRATION_MARKER,
    PYTEST_MANUAL_MARKER,
]
